name: CI

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop", "main"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        rust: ["stable"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
          components: rustfmt, clippy
      - name: Run `cargo check ...`
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose
      - name: Run `cargo fmt ...`
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check --verbose
      - name: Run `cargo clippy ...`
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose
      - name: Run `cargo test ...`
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
